//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalsAndTransforms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignalsAndTransforms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convolve.
        /// </summary>
        public static string BTC_CONVOLUTION {
            get {
                return ResourceManager.GetString("BTC_CONVOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BTN_ADD_SIGNAL {
            get {
                return ResourceManager.GetString("BTN_ADD_SIGNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFT.
        /// </summary>
        public static string BTN_FFT {
            get {
                return ResourceManager.GetString("BTN_FFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal.
        /// </summary>
        public static string BTN_SIGNAL {
            get {
                return ResourceManager.GetString("BTN_SIGNAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convolution Kernel.
        /// </summary>
        public static string CONVOLUTION_PLOT_TITLE {
            get {
                return ResourceManager.GetString("CONVOLUTION_PLOT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency Amplitudes.
        /// </summary>
        public static string PLOT_FREQUENCY_HISTOGRAM_TITLE {
            get {
                return ResourceManager.GetString("PLOT_FREQUENCY_HISTOGRAM_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string RESULT_PLOT_TITLE {
            get {
                return ResourceManager.GetString("RESULT_PLOT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convolution.
        /// </summary>
        public static string RIBBON_CONVOLUTION {
            get {
                return ResourceManager.GetString("RIBBON_CONVOLUTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency Analysis.
        /// </summary>
        public static string RIBBON_FREQUENCY_ANALYSIS {
            get {
                return ResourceManager.GetString("RIBBON_FREQUENCY_ANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Analysis.
        /// </summary>
        public static string RIBBON_TITLE {
            get {
                return ResourceManager.GetString("RIBBON_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1} @ {2} hz at {3} samples/second for {4} seconds..
        /// </summary>
        public static string SAMPLE_DETAILS {
            get {
                return ResourceManager.GetString("SAMPLE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples/Second.
        /// </summary>
        public static string SAMPLING_HZ {
            get {
                return ResourceManager.GetString("SAMPLING_HZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude.
        /// </summary>
        public static string SIGNAL_AMPLITUDE {
            get {
                return ResourceManager.GetString("SIGNAL_AMPLITUDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hz.
        /// </summary>
        public static string SIGNAL_HZ {
            get {
                return ResourceManager.GetString("SIGNAL_HZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal Name.
        /// </summary>
        public static string SIGNAL_NAME {
            get {
                return ResourceManager.GetString("SIGNAL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signal.
        /// </summary>
        public static string SIGNAL_PLOT_TITLE {
            get {
                return ResourceManager.GetString("SIGNAL_PLOT_TITLE", resourceCulture);
            }
        }
    }
}
